<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * personal_access_tokens -> PUBLIC schema (yakuniy to'g'ri joy).
 *
 * MUAMMO: Sanctum bu jadvalни IKKI xil ulanишда ishlatadi:
 *   - token YARATISH ($user->createToken) -> `auth` ulanish (User auth.users'да),
 *   - token O'QISH (auth:sanctum guard kiruvchi Bearer'ni tekshiradi) -> DEFAULT
 *     `pgsql` ulanish (search_path platform,public).
 * Bitta schema ikkalasига ham ko'rinishi kerak. Yagona umumiy — `public`
 * (auth: auth,public | pgsql: platform,public | mahalla: mahalla,master,public).
 * Shu sabab jadval `public`да bo'lishi shart. (Avvalgi auth-schema urinishi
 * yaratishни tuzatgan, ammo o'qishни buzган.)
 */
return new class extends Migration
{
    public function up(): void
    {
        if (config('database.default') !== 'pgsql') {
            return;
        }

        DB::statement(<<<'SQL'
            CREATE TABLE IF NOT EXISTS public.personal_access_tokens (
                id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tokenable_type varchar(255) NOT NULL,
                tokenable_id  uuid NOT NULL,
                name          text NOT NULL,
                token         varchar(64) NOT NULL UNIQUE,
                abilities     text,
                last_used_at  timestamp,
                expires_at    timestamp,
                created_at    timestamp,
                updated_at    timestamp
            )
        SQL);
        DB::statement('CREATE INDEX IF NOT EXISTS pat_tokenable_pub_idx ON public.personal_access_tokens (tokenable_type, tokenable_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS pat_expires_pub_idx ON public.personal_access_tokens (expires_at)');

        // Noto'g'ri joydagi nusxalarni olib tashlaymiz (faqat public qolsin — chalkashlik yo'q).
        DB::statement('DROP TABLE IF EXISTS auth.personal_access_tokens');
        DB::statement('DROP TABLE IF EXISTS platform.personal_access_tokens');
    }

    public function down(): void
    {
        if (config('database.default') !== 'pgsql') {
            return;
        }

        DB::statement('DROP TABLE IF EXISTS public.personal_access_tokens');
    }
};
