<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * personal_access_tokens jadvalini AUTH schemaга ko'chirish.
 *
 * MUAMMO: Original migration (2026_07_17_150921) jadvalni DEFAULT (platform)
 * schemaда yaratgan. Ammo Sanctum token'ni `auth` ulanишида yozadi (User modeli
 * auth.users'да, token shundan meros oladi). `auth` ulanish search_path'i
 * `auth,public` — `platform`ни ko'rmaydi. Natijada mobil login (POST
 * /api/mobile/login) `createToken()`да "relation personal_access_tokens does
 * not exist" (42P01) 500 bilan qulaydi. Prodда jadval umuman yaratilmagan.
 *
 * YECHIM: jadvalni `auth` schemaда (auth ulanish ko'radigan joyда) yaratish.
 * tokenable_id = uuid (auth.users UUID). Eski platform nusxasi (agar bo'lsa,
 * ishlatilmagan — mobil login hech qачон ishlamagan) o'chiriladi.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (config('database.default') !== 'pgsql') {
            return;
        }

        DB::statement(<<<'SQL'
            CREATE TABLE IF NOT EXISTS auth.personal_access_tokens (
                id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tokenable_type varchar(255) NOT NULL,
                tokenable_id  uuid NOT NULL,
                name          text NOT NULL,
                token         varchar(64) NOT NULL UNIQUE,
                abilities     text,
                last_used_at  timestamp,
                expires_at    timestamp,
                created_at    timestamp,
                updated_at    timestamp
            )
        SQL);
        DB::statement('CREATE INDEX IF NOT EXISTS pat_tokenable_idx ON auth.personal_access_tokens (tokenable_type, tokenable_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS pat_expires_idx ON auth.personal_access_tokens (expires_at)');

        // Ishlatilmagan platform nusxasini olib tashlaymiz (chalkashlik bo'lmasin).
        DB::statement('DROP TABLE IF EXISTS platform.personal_access_tokens');
    }

    public function down(): void
    {
        if (config('database.default') !== 'pgsql') {
            return;
        }

        DB::statement('DROP TABLE IF EXISTS auth.personal_access_tokens');
    }
};
